name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: help --info
    - name: Execute Gradle jacocoTestReport
      run: ./gradlew jacocoTestReport --console=plain --build-cache
    - name: Delete jacoco execution data file
      run: rm -r app/build/jacoco/
    - name: Execute Gradle jacocoTestReport from cache
      run: ./gradlew jacocoTestReport --console=plain --build-cache
    - name: assert jacoco execution data file is here
      run: |
        if [ ! -f "app/build/jacoco/test.exec" ]; then
          echo "Jacoco file missing"
          exit 1
        else
          echo "Jacoco file found"
        fi
